import React from "react";
import Head from "next/head";
import { Container, Col, Row, Card } from "react-bootstrap";
import BlogCss from "../../styles/Blog.module.css";
import Image from "next/image";
import GolfHomLogoSmall from "../../../public/images/golfhom_small_logo.svg";
import CategoryIcon from "../../../public/images/vector/category_icon.svg";
import ViwBlogBannerImg from "../../../public/images/view_blog_banner_img.svg";
import { Button } from "antd";
import BottomSection from "../../../common components/bottomGroup";

function ViewBlog() {
  return (
    <>
      <Head>
        <title>Golfhom | View Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://api.tiles.mapbox.com/mapbox-gl-js/v2.13.0/mapbox-gl.css"
          rel="stylesheet"
        />
      </Head>
      {/* VIEW BLOG STARTED */}

      <Container>
        <section className={BlogCss.view_blog_banner_img_section}>
          <p className={BlogCss.view_blog_date}>jan 23, 2023</p>
          <h3 className={BlogCss.view_blog_title}>
            The Circle 15 Genesis Golf Glove View All
          </h3>

          {/* VIEW BLOG JS BANNER IMG */}
          <div className={BlogCss.view_blog_banner_img_container}>
            <Image
              src={ViwBlogBannerImg}
              fill
              alt="banner image golfhom blog"
              className={BlogCss.view_blog_banner_img}
            ></Image>
          </div>
        </section>
      </Container>

      {/*  -----------------------------           BOTTOM IMAGE SECTION         ----------------------------  */}

      <BottomSection />
    </>
  );
}

export default ViewBlog;
