import React from 'react'
import FAQBannerImg from "../../../public/images/faq_banner_img.svg";
import BottomSection from "../../../common components/bottomGroup";
import AddListingCss from "../../styles/dashboard/AddListing.module.css";
import Head from 'next/head';
import Image from 'next/image';
import { Container } from 'react-bootstrap';

const Add_listing = () => {
    return (
        <>
            <Head>
                <title>Golfhom | Add Listing</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/*  -------------------------         BANNER IMAGE FAQ         ------------------------------*/}
            <div className={AddListingCss.banner_img_container}>
                <Image
                    fill
                    className={AddListingCss.banner_img}
                    src={FAQBannerImg}
                    alt="faq golfhom banner image"
                ></Image>
            </div>

            { /*     -------------------------     TEXT AREA      ----------------------------    */}

            <Container>
                <h2 className={AddListingCss.addListing}>Add Listing</h2>

                <h3 className={AddListingCss.info}>Information</h3>

                <hr />
            </Container>

            {/*  -----------------------------           BOTTOM IMAGE SECTION         ----------------------------  */}

            <BottomSection />
        </>
    )
}

export default Add_listing
