import React from "react";
import FAQBannerImg from "../../../public/images/faq_banner_img.svg";
import AddListing04Css from "../../styles/dashboard/AddListing04.module.css";
import ProtectedRoute from "../../../common components/protected_route";
import Head from "next/head";
import Image from "next/image";
import { Col, Container, Row } from "react-bootstrap";
import { Input } from "antd";

const AddListing04 = () => {
  return (
    <>
      <ProtectedRoute>
        <Head>
          <title>Golfhom | Add Listing-04</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/*  -------------------------         BANNER IMAGE FAQ         ------------------------------*/}
        <div className={AddListing04Css.banner_img_container}>
          <Image
            fill
            className={AddListing04Css.banner_img}
            src={FAQBannerImg}
            alt="faq golfhom banner image"
          ></Image>
        </div>

        <Container>
          <Col md={10}>
            <h2 className={AddListing04Css.addListing}>Add Listing</h2>

            <h3 className={AddListing04Css.info}>Features</h3>

            <hr />
          </Col>
        </Container>
      </ProtectedRoute>
    </>
  );
};

export default AddListing04;
