import { useState } from "react";
import AddListing05Css from "../../styles/dashboard/AddListing05.module.css";
import ProtectedRoute from "../../../common components/protected_route";
import Head from "next/head";
import Image from "next/image";
import { Col, Container, Row } from "react-bootstrap";
import { Button, Input, Checkbox, Select, Space, Radio } from "antd";
const { TextArea } = Input;
import React from "react";

const AddListing04 = () => {
  const [RadioSmoking, SetRadiovalueSmoking] = useState(1);
  const [RadioPets, SetRadioPets] = useState(1);

  const [RadioChildren, SetRadioChildren] = useState(1);

  const RadioValueSmoking = (e) => {
    console.log("radio checked", e.target.value);
    SetRadiovalueSmoking(e.target.value);
  };

  const RadioValuePets = (e) => {
    console.log("radio checked", e.target.value);
    SetRadioPets(e.target.value);
  };

  const RadioValueChildren = (e) => {
    console.log("radio checked", e.target.value);
    SetRadioChildren(e.target.value);
  };

  return (
    <>
      <ProtectedRoute>
        <Head>
          <title>Golfhom | Add Listing-05</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/*  -------------------------         BANNER IMAGE FAQ         ------------------------------*/}
        <div>
          <Image
            fill
            className={AddListing05Css.banner_img}
            src="https://golf-hom-latest-assets.s3.amazonaws.com/images/faq_banner_img.png"
            alt="faq golfhom banner image"
          ></Image>
        </div>

        <Container>
          <h3 className={AddListing05Css.addListing}>Add Listing</h3>

          <h4 className={AddListing05Css.info}>Terms & rules</h4>

          <hr />
          <Row>
            <Col md={10}>
              <h5 className={AddListing05Css.title}>Cancellation Policy*</h5>
              <div className={AddListing05Css.checkbox_div}>
                <Checkbox className={AddListing05Css.checkbox}>
                  RELAXED (14/7): Cancellations up to 14 days prior to check-in
                  date, 100% refund, Cancellations 7 days or more before the
                  stay, 50% refund. Less than 7 days, no refund
                </Checkbox>
              </div>
              <div className={AddListing05Css.checkbox_div}>
                <Checkbox className={AddListing05Css.checkbox}>
                  MODERATE (30/14): Cancellations up to 30 days prior to
                  check-in date, 100% refund, Cancellations 14 days or more
                  before the stay, 50% refund. Less than 14 days, no refund
                </Checkbox>
              </div>
              <div className={AddListing05Css.checkbox_div}>
                <Checkbox className={AddListing05Css.checkbox}>
                  STRICT (60/30): Cancellations up to 60 days prior to check-in
                  date, 100% refund, Cancellations 30 days or more before the
                  stay, 50% refund. Less than 30 days, no refund
                </Checkbox>
              </div>
              <div className={AddListing05Css.checkbox_div}>
                <Checkbox className={AddListing05Css.checkbox}>
                  Custom Policy
                </Checkbox>
              </div>

              <div className={AddListing05Css.input_divs}>
                <Input
                  type="text"
                  placeholder="Enter your Cancellation policy
                    "
                  className={AddListing05Css.listing}
                />
              </div>
              <Row>
                <Col md={6}>
                  <h5 className={AddListing05Css.title}>
                    Minimum Nights of a Booking*
                  </h5>

                  <Input
                    type="number"
                    placeholder="Enter the minimum nights 0f a booking(number only)"
                    className={AddListing05Css.listing}
                  />
                </Col>

                <Col md={6}>
                  <h5 className={AddListing05Css.title}>
                    Maximum Nights of a Booking*
                  </h5>

                  <Input
                    type="number"
                    placeholder="Enter the maxmum nights of a booking(number only)"
                    className={AddListing05Css.listing}
                  />
                </Col>
              </Row>

              <Row>
                <Col md={6}>
                  <h5 className={AddListing05Css.title}>Check-in After*</h5>

                  <Select
                    style={{ minWidth: "100%" }}
                    className={AddListing05Css.select_input_checkin}
                    defaultValue="lucy"
                    options={[
                      {
                        value: "jack",
                        label: "Jack",
                      },
                      {
                        value: "lucy",
                        label: "Lucy",
                      },
                      {
                        value: "Yiminghe",
                        label: "yiminghe",
                      },
                    ]}
                  />
                </Col>

                <Col md={6}>
                  <h5 className={AddListing05Css.title}>Check-out Before*</h5>
                  <Select
                    style={{ minWidth: "100%" }}
                    className={AddListing05Css.select_input_checkin}
                    defaultValue="lucy"
                    options={[
                      {
                        value: "jack",
                        label: "Jack",
                      },
                      {
                        value: "lucy",
                        label: "Lucy",
                      },
                      {
                        value: "Yiminghe",
                        label: "yiminghe",
                      },
                    ]}
                  />
                </Col>
              </Row>

              {/* Smoking Allowed Checkbox */}
              <Row className={AddListing05Css.radio_section_main_row}>
                <Col md={4}>
                  <div
                    className={
                      AddListing05Css.radioA_inputs_main_heading_container
                    }
                  >
                    <p className={AddListing05Css.radioA_inputs_main_heading_p}>
                      Smoking allowed?
                    </p>
                  </div>
                </Col>

                <Col md={4} className={AddListing05Css.radio_cols}>
                  <Radio.Group
                    onChange={RadioValueSmoking}
                    value={RadioSmoking}
                    className={AddListing05Css.radio_group_div}
                  >
                    <div className={AddListing05Css.radio_main_div}>
                      <div className={AddListing05Css.radioA}>
                        <Radio
                          className={AddListing05Css.radioA_inputs}
                          value={1}
                        >
                          Yes
                        </Radio>
                      </div>
                    </div>
                  </Radio.Group>
                </Col>

                <Col md={4} className={AddListing05Css.radio_cols}>
                  <Radio.Group
                    onChange={RadioValueSmoking}
                    value={RadioSmoking}
                    className={AddListing05Css.radio_group_div}
                  >
                    <div className={AddListing05Css.radio_main_div}>
                      <div className={AddListing05Css.radioA}>
                        <Radio
                          className={AddListing05Css.radioA_inputs}
                          value={2}
                        >
                          No
                        </Radio>
                      </div>
                    </div>
                  </Radio.Group>
                </Col>
              </Row>

              {/* Pets Allowed Checkbox */}
              <Row className={AddListing05Css.radio_section_main_row}>
                <Col md={4}>
                  <div
                    className={
                      AddListing05Css.radioA_inputs_main_heading_container
                    }
                  >
                    <p className={AddListing05Css.radioA_inputs_main_heading_p}>
                      Pets allowed?
                    </p>
                  </div>
                </Col>

                <Col md={4} className={AddListing05Css.radio_cols}>
                  <Radio.Group
                    onChange={RadioValuePets}
                    value={RadioPets}
                    className={AddListing05Css.radio_group_div}
                  >
                    <div className={AddListing05Css.radio_main_div}>
                      <div className={AddListing05Css.radioA}>
                        <Radio
                          className={AddListing05Css.radioA_inputs}
                          value={3}
                        >
                          Yes
                        </Radio>
                      </div>
                    </div>
                  </Radio.Group>
                </Col>

                <Col md={4} className={AddListing05Css.radio_cols}>
                  <Radio.Group
                    onChange={RadioValuePets}
                    value={RadioPets}
                    className={AddListing05Css.radio_group_div}
                  >
                    <div className={AddListing05Css.radio_main_div}>
                      <div className={AddListing05Css.radioA}>
                        <Radio
                          className={AddListing05Css.radioA_inputs}
                          value={4}
                        >
                          No
                        </Radio>
                      </div>
                    </div>
                  </Radio.Group>
                </Col>
              </Row>

              {/* Children Allowed Checkbox */}
              <Row className={AddListing05Css.radio_section_main_row}>
                <Col md={4}>
                  <div
                    className={
                      AddListing05Css.radioA_inputs_main_heading_container
                    }
                  >
                    <p className={AddListing05Css.radioA_inputs_main_heading_p}>
                      Children allowed?
                    </p>
                  </div>
                </Col>

                <Col md={4} className={AddListing05Css.radio_cols}>
                  <Radio.Group
                    onChange={RadioValueChildren}
                    value={RadioChildren}
                    className={AddListing05Css.radio_group_div}
                  >
                    <div className={AddListing05Css.radio_main_div}>
                      <div className={AddListing05Css.radioA}>
                        <Radio
                          className={AddListing05Css.radioA_inputs}
                          value={5}
                        >
                          Yes
                        </Radio>
                      </div>
                    </div>
                  </Radio.Group>
                </Col>

                <Col md={4} className={AddListing05Css.radio_cols}>
                  <Radio.Group
                    onChange={RadioValueChildren}
                    value={RadioChildren}
                    className={AddListing05Css.radio_group_div}
                  >
                    <div className={AddListing05Css.radio_main_div}>
                      <div className={AddListing05Css.radioA}>
                        <Radio
                          className={AddListing05Css.radioA_inputs}
                          value={6}
                        >
                          No
                        </Radio>
                      </div>
                    </div>
                  </Radio.Group>
                </Col>
              </Row>

              <Row>
                <Col md={12}>
                  <h5 className={AddListing05Css.title}>
                    Additional rules and information (Optional)
                  </h5>
                  <TextArea
                    className={AddListing05Css.text_area}
                    rows={4}
                    placeholder="Write something here..."
                  />
                </Col>
              </Row>

              <div className={AddListing05Css.twobtn}>
                <Button className={AddListing05Css.savebtn}>Back</Button>
                <Button className={AddListing05Css.savebtn}>
                  Save as Draft
                </Button>
              </div>
              <div className={AddListing05Css.addbtnparent}>
                <Button className={AddListing05Css.addbtn}>Continue</Button>
              </div>
            </Col>
          </Row>
        </Container>
      </ProtectedRoute>
    </>
  );
};

export default AddListing04;
