import React, { useState } from "react";
import FAQBannerImg from "../../../public/images/faq_banner_img.svg";
import AddListing02Css from "../../styles/dashboard/AddListing02.module.css";
import ProtectedRoute from "../../../common components/protected_route";
import Head from "next/head";
import Image from "next/image";
import { Col, Container, Row } from "react-bootstrap";
import { Input } from "antd";
import cloud from "../../../public/images/vector/cloud.svg";
import mount from "../../../public/images/vector/mount.svg";

const Addlisting02 = () => {

    return (
        <>
            <ProtectedRoute>
                <Head>
                    <title>Golfhom | Add Listing-02</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                {/*  -------------------------         BANNER IMAGE FAQ         ------------------------------*/}
                <div className={AddListing02Css.banner_img_container}>
                    <Image
                        fill
                        className={AddListing02Css.banner_img}
                        src={FAQBannerImg}
                        alt="faq golfhom banner image"
                    ></Image>
                </div>

                {/*     -------------------------     TEXT AREA      ----------------------------    */}

                <Container>
                    <Col md={9}>
                        <h2 className={AddListing02Css.addListing}>Add Listing</h2>

                        <h3 className={AddListing02Css.info}>Media</h3>

                        <hr />

                        <Row className={AddListing02Css.imgParent}>
                            <div className={AddListing02Css.imageParent}>
                                <Image
                                    src={mount}
                                    alt="mount"
                                    fill
                                    className={AddListing02Css.mount}
                                />
                            </div>
                            <p className={AddListing02Css.para}>Drag and drop the images to customize the gallery order. Please use high resolution images when able, 3840 x 2160 pixels recommended.Click on the star icon to set the featured image</p>
                            <p className={AddListing02Css.mini}>(Minimum size 1440 x 900 px)</p>

                            <div className={AddListing02Css.cloudParent}>
                                <div className={AddListing02Css.cloudImg}>
                                    <Image src={cloud} alt="cloud" fill className={AddListing02Css.mount} />
                                </div>
                                <button className={AddListing02Css.select}>Select and Upload</button>
                            </div>
                        </Row>
                    </Col>

                    <Row>
                        <h3 className={AddListing02Css.info}>Video URL</h3>

                        <Row>
                            <Col md={9}>
                                <Input type="text" placeholder="Select the video link or URL Supported formats: youtube, vimeo, SWF, and MOV" className={AddListing02Css.listing} />
                            </Col>

                            <div className={AddListing02Css.twobtn}>
                                <button className={AddListing02Css.savebtn}>Back</button>
                                <button className={AddListing02Css.savebtn}>Save as Draft</button>
                            </div>

                            <Row className={AddListing02Css.addbtnparent}>
                                <button className={AddListing02Css.addbtn}> Continue</button>
                            </Row>
                        </Row>
                    </Row>
                </Container>
            </ProtectedRoute>
        </>
    )
}

export default Addlisting02
