import React from "react";
import Head from "next/head";
import { Button, Col, Container, Row, Table } from "react-bootstrap";
import IncomeCss from "../../styles/dashboard/Income.module.css";
import Link from "next/link";
import BottomSection from "../../../common components/bottomGroup";

const Income = () => {
  return (
    <>
      <Head>
        <title>Golfhom | Income</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={IncomeCss.income_main_section}>
        <Container>
          <h4 className={IncomeCss.income_page_heading}>Income</h4>

          <section className={IncomeCss.income_page_cards_section}>
            <Row className={IncomeCss.income_page_cards_rows}>
              <Col md={4} className={IncomeCss.income_page_cards_cols}>
                <div className={IncomeCss.income_page_cards_container}>
                  <div className={IncomeCss.income_page_cards_text_container}>
                    <h4 className={IncomeCss.income_page_cards_heading}>
                      From $0
                    </h4>
                    <p className={IncomeCss.income_page_cards_subheading}>
                      Total Earnings
                    </p>
                    <p className={IncomeCss.income_page_cards_desc}>
                      Excluding the service fee, the host fee and the security
                      deposit
                    </p>
                  </div>

                  <div className={IncomeCss.income_page_cards_btn_container}>
                    <Link
                      href="/"
                      className={IncomeCss.income_page_cards_links}
                    >
                      <Button
                        className={IncomeCss.income_page_cards_btn}
                        type="primary"
                      >
                        Details
                      </Button>
                    </Link>
                  </div>
                </div>
              </Col>
              <Col md={4} className={IncomeCss.income_page_cards_cols}>
                <div className={IncomeCss.income_page_cards_container}>
                  <div className={IncomeCss.income_page_cards_text_container}>
                    <h4 className={IncomeCss.income_page_cards_heading}>
                      From $0
                    </h4>
                    <p className={IncomeCss.income_page_cards_subheading}>
                      Available Balance
                    </p>
                    <p className={IncomeCss.income_page_cards_desc}>
                      Gofhom.com will normally remit rental income to the host
                      as directed approximately 2 business days after the agreed
                      upon check-in date (if no complaints have been
                      registered).
                    </p>
                  </div>

                  <div className={IncomeCss.income_page_cards_btn_container}>
                    <Link
                      href="/"
                      className={IncomeCss.income_page_cards_links}
                    >
                      <Button
                        className={IncomeCss.income_page_cards_btn}
                        type="primary"
                      >
                        Read FAQ
                      </Button>
                    </Link>
                  </div>
                </div>
              </Col>
              <Col md={4} className={IncomeCss.income_page_cards_cols}>
                <div className={IncomeCss.income_page_cards_container}>
                  <div className={IncomeCss.income_page_cards_text_container}>
                    <h4 className={IncomeCss.income_page_cards_heading}>
                      From $0
                    </h4>
                    <p className={IncomeCss.income_page_cards_subheading}>
                      Total reservations
                    </p>
                    <p className={IncomeCss.income_page_cards_desc}>
                      Represents the total number of paid reservations you have
                      received
                    </p>
                  </div>

                  <div className={IncomeCss.income_page_cards_btn_container}>
                    <Link
                      href="/"
                      className={IncomeCss.income_page_cards_links}
                    >
                      <Button
                        className={IncomeCss.income_page_cards_btn}
                        type="primary"
                      >
                        Manage
                      </Button>
                    </Link>
                  </div>
                </div>
              </Col>
            </Row>
          </section>

          <section className={IncomeCss.income_page_payout_section}>
            <div className={IncomeCss.income_page_payout_rows}>
              <div className={IncomeCss.income_page_payout_cols}>
                <div className={IncomeCss.income_page_payout_heading_container}>
                  <h4 className={IncomeCss.income_page_payout_heading}>
                    Earnings
                  </h4>
                </div>
                <hr className={IncomeCss.income_page_payout_hr} />
                <div
                  className={IncomeCss.income_page_payout_subheading_container}
                >
                  <p className={IncomeCss.income_page_payout_subheading}>
                    At the moment there are no earnings.
                  </p>
                </div>
              </div>
            </div>

            <div className={IncomeCss.income_page_payout_rows}>
              <div className={IncomeCss.income_page_payout_cols}>
                <div className={IncomeCss.income_page_payout_heading_container}>
                  <h4 className={IncomeCss.income_page_payout_heading}>
                    Payouts
                  </h4>

                  <p className={IncomeCss.income_page_payout_method}>
                    Setup Payout Method
                  </p>
                </div>
                <hr className={IncomeCss.income_page_payout_hr} />
                <div
                  className={IncomeCss.income_page_payout_subheading_container}
                >
                  <p className={IncomeCss.income_page_payout_subheading}>
                    At the moment there are no earnings.
                  </p>
                </div>
              </div>
            </div>
          </section>
        </Container>
      </main>
      {/*  ---------------------------           BOTTOM IMAGE SECTION         ----------------------------  */}
      <BottomSection />
    </>
  );
};

export default Income;
