/* eslint-disable react/no-unescaped-entities */
import React, { useState } from "react";
import BottomSection from "../../../common components/bottomGroup";
import MessageCss from "../../styles/dashboard/message.module.css";
import Image from "next/image";
import Laugh from "../../../public/images/laugh.png";
import { Container } from "react-bootstrap";
import Head from "next/head";
import ProtectedRoute from "../../../common components/protected_route";
import { Select, Space, Typography } from "antd";

const Messages = () => {

  return (
    <>
      <ProtectedRoute>
        <Head>
          <title>Golfhom | Messages</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* ---------------------------       BANNER IMAGE SECTION      --------------------------  */}
        <div className={MessageCss.laughContainer}>
          <Image
            fill
            className={MessageCss.laughimg}
            src={Laugh}
            alt="Laugh"
          ></Image>
        </div>

        {/*     -------------------------     TEXT AREA      ----------------------------    */}

        <Container>
          <h3 className={MessageCss.messages}>Messages</h3>
          <div className={MessageCss.formSort}>
            <h4 className={MessageCss.form}>Form</h4>

            <div className={MessageCss.sortDown}>
              <h4 className={MessageCss.form}>Sort</h4>
              <Select
                defaultValue="Asc"
                options={[
                  {
                    value: "900",
                    label: "900",
                  },
                  {
                    value: "1000",
                    label: "1000",
                  },
                ]}
                trigger={["click"]}
                className={MessageCss.asc}
                size="large"
              >
                <Select.Option
                  onClick={(e) => e.preventDefault()}
                >
                  <Typography.Link>
                    <Space
                    >Asc
                    </Space>
                  </Typography.Link>
                </Select.Option>
              </Select>
            </div>
          </div>

          <p className={MessageCss.para}>
            You don't have any message at this moment.
          </p>
        </Container>

        {/*  -----------------------------           BOTTOM IMAGE SECTION         ----------------------------  */}

        <BottomSection />
      </ProtectedRoute>
    </>
  );
};

export default Messages;
