import { React, Suspense } from "react";
import ReservationCss from "../../styles/dashboard/Reservation.module.css";
import Image from "next/image";
import { Button, Container, Table } from "react-bootstrap";
import Profile from "../../../public/images/vector/profile.svg";
import Head from "next/head";
import ProtectedRoute from "../../../common components/protected_route";
import dynamic from "next/dynamic";
const BottomSection = dynamic(
  () => import("../../../common components/bottomGroup"),
  {
    suspense: true,
  }
);
const Reservation = () => {
  return (
    <>
      <ProtectedRoute>
        <Head>
          <title>Golfhom | Reservation</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/*   -------------------------     BANNER IMAGE   -------------------------------   */}
        <div className={ReservationCss.banner_img_container}>
          <Image
            fill
            className={ReservationCss.banner_img}
            src="https://golf-hom-latest-assets.s3.amazonaws.com/images/faq_banner_img.png"
            alt="faq golfhom banner image"
          ></Image>
        </div>

        {/*     -------------------------     TEXT AREA      ----------------------------    */}

        <Container>
          <h3 className={ReservationCss.reservation}>Reservations</h3>

          <h4 className={ReservationCss.manage}>Manage</h4>

          <Table responsive className={ReservationCss.bodyRow}>
            <thead className={ReservationCss.heading}>
              <tr className={ReservationCss.tableHead}>
                <th className={ReservationCss.blank}></th>
                <th className={ReservationCss.id}>ID</th>
                <th className={ReservationCss.status}>Status</th>
                <th className={ReservationCss.date}>Date</th>
                <th className={ReservationCss.address}>Address</th>
                <th className={ReservationCss.checkin}>Check-in</th>
                <th className={ReservationCss.checkout}>Check-out</th>
                <th className={ReservationCss.guest}>Guests</th>
                <th className={ReservationCss.pet}>Pets</th>
                <th className={ReservationCss.subtotal}>Subtotal</th>
                <th className={ReservationCss.action}>Actions</th>
              </tr>
            </thead>

            <tbody>
              <tr className={ReservationCss.tableRow}>
                <td className={ReservationCss.imgChild}>
                  <Image
                    src={Profile}
                    alt="Profile"
                    fill
                    className={ReservationCss.imageChild}
                  ></Image>
                </td>

                <td>#66628</td>
                <td>
                  <Button className={ReservationCss.under}>Under Review</Button>
                </td>
                <td>April 6, 20237:38 am</td>
                <td>
                  <span className={ReservationCss.oldTown}>
                    {" "}
                    Old Town’s Farm to Table{" "}
                  </span>
                  6826 E 5th St, Scottsdale, Arizona, United States
                </td>
                <td>05-16-2023 Stay</td>
                <td>05-20-2023 Stay</td>
                <td>5 Stay</td>
                <td>Yes</td>
                <td className={ReservationCss.form}>From $6,386.06</td>
                <td>
                  <Button className={ReservationCss.detailBtn}>Details</Button>
                </td>
              </tr>

              <tr className={ReservationCss.tableRow}>
                <td className={ReservationCss.imgChild}>
                  <Image
                    src={Profile}
                    alt="Profile"
                    fill
                    className={ReservationCss.imageChild}
                  ></Image>
                </td>

                <td>#66612</td>
                <td>
                  <Button className={ReservationCss.Completed}>
                    Completed
                  </Button>
                </td>
                <td>April 6, 20237:38 am</td>
                <td>
                  <span className={ReservationCss.oldTown}>
                    {" "}
                    Old Town’s Farm to Table{" "}
                  </span>
                  6826 E 5th St, Scottsdale, Arizona, United States
                </td>
                <td>05-16-2023 Stay</td>
                <td>05-20-2023 Stay</td>
                <td>5 Stay</td>
                <td>No</td>
                <td className={ReservationCss.dollar}>From $6,386.06</td>
                <td>
                  <Button className={ReservationCss.detailBtn}>Details</Button>
                </td>
              </tr>

              <tr className={ReservationCss.tableRow}>
                <td className={ReservationCss.imgChild}>
                  <Image
                    src={Profile}
                    alt="Profile"
                    fill
                    className={ReservationCss.imageChild}
                  ></Image>
                </td>

                <td>#66629</td>
                <td>
                  <Button className={ReservationCss.expired}>Expired</Button>
                </td>
                <td>April 6, 20237:38 am</td>
                <td>
                  <span className={ReservationCss.oldTown}>
                    {" "}
                    Old Town’s Farm to Table{" "}
                  </span>
                  6826 E 5th St, Scottsdale, Arizona, United States
                </td>
                <td>05-16-2023 Stay</td>
                <td>05-20-2023 Stay</td>
                <td>5 Stay</td>
                <td>Yes</td>
                <td className={ReservationCss.dollar}>From $6,386.06</td>
                <td>
                  <Button className={ReservationCss.detailBtn}>Details</Button>
                </td>
              </tr>
            </tbody>
          </Table>
        </Container>

        {/*  -----------------------------           BOTTOM IMAGE SECTION         ----------------------------  */}

        <BottomSection />
      </ProtectedRoute>
    </>
  );
};

export default Reservation;
