import { React, useState, useEffect, useContext } from "react";
import ReservationCss from "../../styles/dashboard/Reservation.module.css";
import Image from "next/image";
import { Button, Container, Table } from "react-bootstrap";
import Profile from "../../../public/images/vector/profile.svg";
import Head from "next/head";
import ProtectedRoute from "../../../common components/protected_route";
import dynamic from "next/dynamic";
import axios from "axios";
import { AuthContext } from "@/context/auth_context";
import NoReservation from "../../../public/images/vector/golf-hole.png";

const BottomSection = dynamic(
  () => import("../../../common components/bottomGroup"),
  {
    suspense: true,
  }
);

const Reservation = () => {
  const ContextUserDetails = useContext(AuthContext);
  const [AllBookingData, setAllBookingData] = useState([{}]);

  useEffect(() => {
    const GetAllBookings = async () => {
      try {
        const GetAllBookingRes = await axios.get(
          `${process.env.NEXT_PUBLIC_API_URL}/v1/booking/getMyBooking?limit=10&page=1`,
          {
            headers: {
              Authorization: `Bearer ${ContextUserDetails.UserState}`,
            },
          }
        );

        if (GetAllBookingRes.status === 200) {
          setAllBookingData([]);
          console.log(GetAllBookingRes.data.data, "MY BOOKING DATA");
        }
      } catch (error) {
        console.log(error, "ERROR IN GET ALL BOOKINGS");
      }
    };
    GetAllBookings();

    return () => {};
  }, [ContextUserDetails]);

  return (
    <>
      <ProtectedRoute>
        <Head>
          <title>Golfhom | Reservation</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/*   -------------------------     BANNER IMAGE   -------------------------------   */}
        <div>
          <Image
            fill
            className={ReservationCss.banner_img}
            src="https://golf-hom-latest-assets.s3.amazonaws.com/images/faq_banner_img.png"
            alt="faq golfhom banner image"
          ></Image>
        </div>

        {/*     -------------------------     TEXT AREA      ----------------------------    */}

        <Container>
          <h3 className={ReservationCss.reservation}>Reservations</h3>

          {/* <h4 className={ReservationCss.manage}>Manage</h4> */}
          <Table responsive className={ReservationCss.bodyRow}>
            <thead className={ReservationCss.heading}>
              <tr className={ReservationCss.tableHead}>
                <th className={ReservationCss.blank}></th>
                <th className={ReservationCss.id}>ID</th>
                <th className={ReservationCss.status}>Status</th>
                <th className={ReservationCss.date}>Date</th>
                <th className={ReservationCss.address}>Address</th>
                <th className={ReservationCss.checkin}>Check-in</th>
                <th className={ReservationCss.checkout}>Check-out</th>
                <th className={ReservationCss.guest}>Guests</th>
                <th className={ReservationCss.pet}>Pets</th>
                <th className={ReservationCss.subtotal}>Subtotal</th>
                {/* <th className={ReservationCss.action}>Actions</th> */}
              </tr>
            </thead>
            {AllBookingData.length === 0 ? (
              <tbody>
                <div className={ReservationCss.no_reservation_img_div}>
                  <Image
                    width={70}
                    height={70}
                    src={NoReservation}
                    alt="No Reservation!"
                    className={ReservationCss.no_reservation_img}
                  ></Image>
                  <p className={ReservationCss.no_reservation_text}>
                    No Reservation!
                  </p>
                </div>
              </tbody>
            ) : (
              ""
            )}

            <tbody>
              {AllBookingData ? (
                <tr className={ReservationCss.tableRow}>
                  <td className={ReservationCss.imgChild}>
                    <Image
                      src={Profile}
                      alt="Profile"
                      fill
                      className={ReservationCss.imageChild}
                    ></Image>
                  </td>

                  <td>#66628</td>
                  <td>
                    <Button className={ReservationCss.under}>
                      Under Review
                    </Button>
                  </td>
                  <td>April 6, 20237:38 am</td>
                  <td>
                    <span className={ReservationCss.oldTown}>
                      {" "}
                      Old Town’s Farm to Table{" "}
                    </span>
                    6826 E 5th St, Scottsdale, Arizona, United States
                  </td>
                  <td>05-16-2023 Stay</td>
                  <td>05-20-2023 Stay</td>
                  <td>5 Stay</td>
                  <td>Yes</td>
                  <td className={ReservationCss.form}>From $6,386.06</td>
                  {/* <td>
              <Button className={ReservationCss.detailBtn}>Details</Button>
            </td> */}
                </tr>
              ) : (
                ""
              )}
            </tbody>
          </Table>
        </Container>

        {/*  -----------------------------           BOTTOM IMAGE SECTION         ----------------------------  */}

        <BottomSection />
      </ProtectedRoute>
    </>
  );
};

export default Reservation;
