import React from "react";
import UserProfieCss from "../../styles/dashboard/UserProfile.module.css";
import { Container, Col, Row, Card } from "react-bootstrap";
import Head from "next/head";
import UserImg from "../../../public/images/user_img.webp";
import Image from "next/image";
import { Input, Button } from "antd";
const { TextArea } = Input;
import ProtectedRoute from "../../../common components/protected_route";

const UserProfile = () => {
  return (
    <>
      <ProtectedRoute>
        <Head>
          <title>Golfhom | User Profile</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={UserProfieCss.user_profile_main_section}>
          <Container>
            {/* PROFILE PAGE MAIN HEADING */}
            <h3 className={UserProfieCss.user_profile_page_heading}>Profile</h3>

            <section className={UserProfieCss.user_profile_page_info_section}>
              {/* PROFILE SECTION */}
              <div className={UserProfieCss.user_profile_photo_container}>
                <h4 className={UserProfieCss.user_profile_page_section_heading}>
                  Photo
                </h4>
                <div className={UserProfieCss.user_profile_page_pic_container}>
                  <Image
                    src={UserImg}
                    height={160}
                    width={160}
                    className={UserProfieCss.user_profile_page_pic}
                    alt="Profile pic"
                  ></Image>
                </div>
              </div>
            </section>

            {/* INFORMATION SECTION */}
            <section className={UserProfieCss.user_profile_page_info_section}>
              <h5 className={UserProfieCss.user_profile_page_section_heading}>
                Information
              </h5>
              <hr className={UserProfieCss.user_profile_page_hr} />
              <Row className={UserProfieCss.user_profile_page_rows}>
                <Col md={5} className={UserProfieCss.user_profile_page_cols}>
                  {/* DIV 1 */}
                  <div
                    className={UserProfieCss.user_profile_page_info_input_div}
                  >
                    <label
                      className={
                        UserProfieCss.user_profile_page_info_input_label
                      }
                      htmlFor=""
                    >
                      User Name
                    </label>
                    <Input
                      className={UserProfieCss.user_profile_page_info_input}
                      placeholder="Basic usage"
                    />
                  </div>

                  {/* DIV 2 */}
                  <div
                    className={UserProfieCss.user_profile_page_info_input_div}
                  >
                    <label
                      className={
                        UserProfieCss.user_profile_page_info_input_label
                      }
                      htmlFor=""
                    >
                      First Name
                    </label>
                    <Input
                      className={UserProfieCss.user_profile_page_info_input}
                      placeholder="Basic usage"
                    />
                  </div>

                  {/* DIV 3 */}
                  <div
                    className={UserProfieCss.user_profile_page_info_input_div}
                  >
                    <label
                      className={
                        UserProfieCss.user_profile_page_info_input_label
                      }
                      htmlFor=""
                    >
                      Native Language
                    </label>
                    <Input
                      className={UserProfieCss.user_profile_page_info_input}
                      placeholder="Basic usage"
                    />
                  </div>
                </Col>
                <Col md={5} className={UserProfieCss.user_profile_page_cols}>
                  {/* DIV 1 */}
                  <div
                    className={UserProfieCss.user_profile_page_info_input_div}
                  >
                    <label
                      className={
                        UserProfieCss.user_profile_page_info_input_label
                      }
                      htmlFor=""
                    >
                      Display Name Publicly as
                    </label>
                    <Input
                      className={UserProfieCss.user_profile_page_info_input}
                      placeholder="Basic usage"
                    />
                  </div>

                  {/* DIV 2 */}
                  <div
                    className={UserProfieCss.user_profile_page_info_input_div}
                  >
                    <label
                      className={
                        UserProfieCss.user_profile_page_info_input_label
                      }
                      htmlFor=""
                    >
                      Last Name
                    </label>
                    <Input
                      className={UserProfieCss.user_profile_page_info_input}
                      placeholder="Basic usage"
                    />
                  </div>

                  {/* DIV 3 */}
                  <div
                    className={UserProfieCss.user_profile_page_info_input_div}
                  >
                    <label
                      className={
                        UserProfieCss.user_profile_page_info_input_label
                      }
                      htmlFor=""
                    >
                      Other Language
                    </label>
                    <Input
                      className={UserProfieCss.user_profile_page_info_input}
                      placeholder="Basic usage"
                    />
                  </div>
                </Col>
                {/* INPUT TEXT AREA */}
                <div className={UserProfieCss.user_profile_page_info_input_div}>
                  <label
                    className={UserProfieCss.user_profile_page_info_input_label}
                    htmlFor=""
                  >
                    Bio
                  </label>
                  <TextArea
                    rows={4}
                    className={UserProfieCss.user_profile_page_info_input}
                  />
                </div>

                {/* SAVE BTN CONTAINER */}
                <div
                  className={UserProfieCss.user_profile_page_save_btn_container}
                >
                  <Button
                    className={UserProfieCss.user_profile_page_save_btn}
                    type="primary"
                  >
                    Save
                  </Button>
                </div>
              </Row>
            </section>

            {/* ADDRESS SECTION */}
            <section className={UserProfieCss.user_profile_page_info_section}>
              <h5 className={UserProfieCss.user_profile_page_section_heading}>
                Address
              </h5>
              <hr className={UserProfieCss.user_profile_page_hr} />
              <Row className={UserProfieCss.user_profile_page_rows}>
                <Col md={5} className={UserProfieCss.user_profile_page_cols}>
                  {/* DIV 1 */}
                  <div
                    className={UserProfieCss.user_profile_page_info_input_div}
                  >
                    <label
                      className={
                        UserProfieCss.user_profile_page_info_input_label
                      }
                      htmlFor=""
                    >
                      Street Address
                    </label>
                    <Input
                      className={UserProfieCss.user_profile_page_info_input}
                      placeholder="Basic usage"
                    />
                  </div>

                  {/* DIV 2 */}
                  <div
                    className={UserProfieCss.user_profile_page_info_input_div}
                  >
                    <label
                      className={
                        UserProfieCss.user_profile_page_info_input_label
                      }
                      htmlFor=""
                    >
                      City
                    </label>
                    <Input
                      className={UserProfieCss.user_profile_page_info_input}
                      placeholder="Basic usage"
                    />
                  </div>

                  {/* DIV 3 */}
                  <div
                    className={UserProfieCss.user_profile_page_info_input_div}
                  >
                    <label
                      className={
                        UserProfieCss.user_profile_page_info_input_label
                      }
                      htmlFor=""
                    >
                      Zip Code
                    </label>
                    <Input
                      className={UserProfieCss.user_profile_page_info_input}
                      placeholder="Basic usage"
                    />
                  </div>

                  {/* DIV 4 */}
                  <div
                    className={UserProfieCss.user_profile_page_info_input_div}
                  >
                    <label
                      className={
                        UserProfieCss.user_profile_page_info_input_label
                      }
                      htmlFor=""
                    >
                      Country
                    </label>
                    <Input
                      className={UserProfieCss.user_profile_page_info_input}
                      placeholder="Basic usage"
                    />
                  </div>
                </Col>
                <Col md={5} className={UserProfieCss.user_profile_page_cols}>
                  {/* DIV 1 */}
                  <div
                    className={UserProfieCss.user_profile_page_info_input_div}
                  >
                    <label
                      className={
                        UserProfieCss.user_profile_page_info_input_label
                      }
                      htmlFor=""
                    >
                      Apt, Suite
                    </label>
                    <Input
                      className={UserProfieCss.user_profile_page_info_input}
                      placeholder="Basic usage"
                    />
                  </div>

                  {/* DIV 2 */}
                  <div
                    className={UserProfieCss.user_profile_page_info_input_div}
                  >
                    <label
                      className={
                        UserProfieCss.user_profile_page_info_input_label
                      }
                      htmlFor=""
                    >
                      State
                    </label>
                    <Input
                      className={UserProfieCss.user_profile_page_info_input}
                      placeholder="Basic usage"
                    />
                  </div>

                  {/* DIV 3 */}
                  <div
                    className={UserProfieCss.user_profile_page_info_input_div}
                  >
                    <label
                      className={
                        UserProfieCss.user_profile_page_info_input_label
                      }
                      htmlFor=""
                    >
                      Neighborhood
                    </label>
                    <Input
                      className={UserProfieCss.user_profile_page_info_input}
                      placeholder="Basic usage"
                    />
                  </div>
                </Col>

                {/* SAVE BTN CONTAINER */}
                <div
                  className={UserProfieCss.user_profile_page_save_btn_container}
                >
                  <Button
                    className={UserProfieCss.user_profile_page_save_btn}
                    type="primary"
                  >
                    Save
                  </Button>
                </div>
              </Row>
            </section>

            {/* PHONE SECTION */}
            <section className={UserProfieCss.user_profile_page_info_section}>
              <h5 className={UserProfieCss.user_profile_page_section_heading}>
                Phone
              </h5>
              <hr className={UserProfieCss.user_profile_page_hr} />
              <Row className={UserProfieCss.user_profile_page_rows}>
                <Col md={5} className={UserProfieCss.user_profile_page_cols}>
                  {/* DIV 1 */}
                  <div
                    className={UserProfieCss.user_profile_page_info_input_div}
                  >
                    <label
                      className={
                        UserProfieCss.user_profile_page_info_input_label
                      }
                      htmlFor=""
                    >
                      Contact Name
                    </label>
                    <Input
                      className={UserProfieCss.user_profile_page_info_input}
                      placeholder="Basic usage"
                    />
                  </div>

                  {/* DIV 2 */}
                  <div
                    className={UserProfieCss.user_profile_page_info_input_div}
                  >
                    <label
                      className={
                        UserProfieCss.user_profile_page_info_input_label
                      }
                      htmlFor=""
                    >
                      Email
                    </label>
                    <Input
                      className={UserProfieCss.user_profile_page_info_input}
                      placeholder="Basic usage"
                    />
                  </div>
                </Col>
                <Col md={5} className={UserProfieCss.user_profile_page_cols}>
                  {/* DIV 1 */}
                  <div
                    className={UserProfieCss.user_profile_page_info_input_div}
                  >
                    <label
                      className={
                        UserProfieCss.user_profile_page_info_input_label
                      }
                      htmlFor=""
                    >
                      Relationship
                    </label>
                    <Input
                      className={UserProfieCss.user_profile_page_info_input}
                      placeholder="Basic usage"
                    />
                  </div>

                  {/* DIV 2 */}
                  <div
                    className={UserProfieCss.user_profile_page_info_input_div}
                  >
                    <label
                      className={
                        UserProfieCss.user_profile_page_info_input_label
                      }
                      htmlFor=""
                    >
                      Phone
                    </label>
                    <Input
                      className={UserProfieCss.user_profile_page_info_input}
                      placeholder="Basic usage"
                    />
                  </div>
                </Col>

                {/* SAVE BTN CONTAINER */}
                <div
                  className={UserProfieCss.user_profile_page_save_btn_container}
                >
                  <Button
                    className={UserProfieCss.user_profile_page_save_btn}
                    type="primary"
                  >
                    Save
                  </Button>
                </div>
              </Row>
            </section>

            {/* SOCIAL MEDIA */}
            <section className={UserProfieCss.user_profile_page_info_section}>
              <h5 className={UserProfieCss.user_profile_page_section_heading}>
                Social Media
              </h5>
              <hr className={UserProfieCss.user_profile_page_hr} />
              <Row className={UserProfieCss.user_profile_page_rows}>
                <Col md={5} className={UserProfieCss.user_profile_page_cols}>
                  {/* DIV 1 */}
                  <div
                    className={UserProfieCss.user_profile_page_info_input_div}
                  >
                    <label
                      className={
                        UserProfieCss.user_profile_page_info_input_label
                      }
                      htmlFor=""
                    >
                      Facebook URL
                    </label>
                    <Input
                      className={UserProfieCss.user_profile_page_info_input}
                      placeholder="Basic usage"
                    />
                  </div>

                  {/* DIV 2 */}
                  <div
                    className={UserProfieCss.user_profile_page_info_input_div}
                  >
                    <label
                      className={
                        UserProfieCss.user_profile_page_info_input_label
                      }
                      htmlFor=""
                    >
                      Linkedin URL
                    </label>
                    <Input
                      className={UserProfieCss.user_profile_page_info_input}
                      placeholder="Basic usage"
                    />
                  </div>

                  {/* DIV 3 */}
                  <div
                    className={UserProfieCss.user_profile_page_info_input_div}
                  >
                    <label
                      className={
                        UserProfieCss.user_profile_page_info_input_label
                      }
                      htmlFor=""
                    >
                      Instagram URL
                    </label>
                    <Input
                      className={UserProfieCss.user_profile_page_info_input}
                      placeholder="Basic usage"
                    />
                  </div>

                  {/* DIV 4 */}
                  <div
                    className={UserProfieCss.user_profile_page_info_input_div}
                  >
                    <label
                      className={
                        UserProfieCss.user_profile_page_info_input_label
                      }
                      htmlFor=""
                    >
                      Youtube Url
                    </label>
                    <Input
                      className={UserProfieCss.user_profile_page_info_input}
                      placeholder="Basic usage"
                    />
                  </div>

                  {/* DIV 5 */}
                  <div
                    className={UserProfieCss.user_profile_page_info_input_div}
                  >
                    <label
                      className={
                        UserProfieCss.user_profile_page_info_input_label
                      }
                      htmlFor=""
                    >
                      Airbnb Url
                    </label>
                    <Input
                      className={UserProfieCss.user_profile_page_info_input}
                      placeholder="Basic usage"
                    />
                  </div>
                </Col>
                <Col md={5} className={UserProfieCss.user_profile_page_cols}>
                  {/* DIV 1 */}
                  <div
                    className={UserProfieCss.user_profile_page_info_input_div}
                  >
                    <label
                      className={
                        UserProfieCss.user_profile_page_info_input_label
                      }
                      htmlFor=""
                    >
                      Twitter URL
                    </label>
                    <Input
                      className={UserProfieCss.user_profile_page_info_input}
                      placeholder="Basic usage"
                    />
                  </div>

                  {/* DIV 2 */}
                  <div
                    className={UserProfieCss.user_profile_page_info_input_div}
                  >
                    <label
                      className={
                        UserProfieCss.user_profile_page_info_input_label
                      }
                      htmlFor=""
                    >
                      Google Plus Url
                    </label>
                    <Input
                      className={UserProfieCss.user_profile_page_info_input}
                      placeholder="Basic usage"
                    />
                  </div>

                  {/* DIV 3 */}
                  <div
                    className={UserProfieCss.user_profile_page_info_input_div}
                  >
                    <label
                      className={
                        UserProfieCss.user_profile_page_info_input_label
                      }
                      htmlFor=""
                    >
                      Pinterest Url
                    </label>
                    <Input
                      className={UserProfieCss.user_profile_page_info_input}
                      placeholder="Basic usage"
                    />
                  </div>

                  {/* DIV 4 */}
                  <div
                    className={UserProfieCss.user_profile_page_info_input_div}
                  >
                    <label
                      className={
                        UserProfieCss.user_profile_page_info_input_label
                      }
                      htmlFor=""
                    >
                      Vimeo Url
                    </label>
                    <Input
                      className={UserProfieCss.user_profile_page_info_input}
                      placeholder="Basic usage"
                    />
                  </div>

                  {/* DIV 5 */}
                  <div
                    className={UserProfieCss.user_profile_page_info_input_div}
                  >
                    <label
                      className={
                        UserProfieCss.user_profile_page_info_input_label
                      }
                      htmlFor=""
                    >
                      Trip Advisor Url
                    </label>
                    <Input
                      className={UserProfieCss.user_profile_page_info_input}
                      placeholder="Basic usage"
                    />
                  </div>
                </Col>

                {/* SAVE BTN CONTAINER */}
                <div
                  className={UserProfieCss.user_profile_page_save_btn_container}
                >
                  <Button
                    className={UserProfieCss.user_profile_page_save_btn}
                    type="primary"
                  >
                    Save
                  </Button>
                </div>
              </Row>
            </section>
          </Container>
        </main>
      </ProtectedRoute>
    </>
  );
};

export default UserProfile;
