import React from "react";
import Head from "next/head";
import { Button, Space } from "antd";
import Link from "next/link";

const About = () => {
  return (
    <>
      <Head>
        <title>Golfhom | About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>About Page</h1>

      <div>
        <Space wrap>
          <Link href="/home">
            <Button type="primary" Link>
              Home Page
            </Button>
          </Link>
        </Space>
      </div>
    </>
  );
};

export default About;
