import React from "react";
import { Container, Col, Row, Card } from "react-bootstrap";
import ContactUsCss from "../styles/ContactUs.module.css";
import Head from "next/head";
import ContactUsBannerImage from "../../public/images/contact_us_banner_img.svg";
import Image from "next/image";
import { Button, Input } from "antd";
const { TextArea } = Input;
import ManThumbsUpImg from "../../public/images/contact_us_thumbs_up_man.svg";
import BottomSection from "../../common components/bottomGroup";

const ContactUs = () => {
  return (
    <>
      <Head>
        <title>Golfhom | Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={ContactUsCss.contact_us_main_section}>
        {/* BANNER IMAGE SECTION */}
        <div className={ContactUsCss.contact_us_bannerimg_container}>
          <Image
            fill
            className={ContactUsCss.contact_us_bannerimg}
            src={ContactUsBannerImage}
            alt="Banner image contact us"
            priority
          ></Image>
        </div>

        <Container className={ContactUsCss.parent_container}>
          <Col md={7} className={ContactUsCss.contact_us_input_section}>
            <h3 className={ContactUsCss.contact_us_input_heading}>
              Contact Us
            </h3>

            <p className={ContactUsCss.contact_us_input_subheading}>
              Questions or Comments?
            </p>

            <p className={ContactUsCss.contact_our_staff_text}>
              Please contact our staff via the form below. We will respond as
              soon as we’re able.
            </p>

            {/* INPUTS */}
            <div className={ContactUsCss.contact_us_input_container}>
              <label className={ContactUsCss.input_label}>Name</label>
              <Input
                className={ContactUsCss.contact_us_input}
                size="large"
                placeholder="Enter Your name"
              />
            </div>

            {/* INPUTSS */}
            <div className={ContactUsCss.contact_us_input_container}>
              <label className={ContactUsCss.input_label}>Email</label>
              <Input
                type="email"
                className={ContactUsCss.contact_us_input}
                size="large"
                placeholder="Enter Your email"
              />
            </div>

            {/* INPUTS */}
            <div className={ContactUsCss.contact_us_input_container}>
              <label className={ContactUsCss.input_label}>Subject</label>
              <Input
                className={ContactUsCss.contact_us_input}
                size="large"
                placeholder="Enter Your subject"
              />
            </div>

            {/* INPUTS */}
            <div className={ContactUsCss.contact_us_input_container}>
              <label className={ContactUsCss.input_label}>Message</label>
              <TextArea className={ContactUsCss.input_textarea} rows={4} />
            </div>

            <div className={ContactUsCss.contact_us_input_container}>
              <Button className={ContactUsCss.contact_us_send_btn}>Send</Button>
            </div>
          </Col>
        </Container>

        {/*  -----------------------------           BOTTOM IMAGE SECTION         ----------------------------  */}

        <BottomSection />
      </main>
    </>
  );
};

export default ContactUs;
