import Head from "next/head";
import Index from "./home";

export default function Home() {
  return (
    <>
      <Head>
        <title>Golfhom</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v2.13.0/mapbox-gl.css' rel='stylesheet' />
      </Head>
      <main>
        <Index />
      </main>
    </>
  );
}
