/* eslint-disable react/no-unescaped-entities */
import { useState } from "react";
import RegisterToHost from "../styles/RegisterToHost.module.css";
import Image from "next/image";
import { Button, Col, Container, Row } from "react-bootstrap";
import { Checkbox, Input } from "antd";
import Head from "next/head";
import Link from "next/link";
import dynamic from "next/dynamic";
const BottomSection = dynamic(
  () => import("../../common components/bottomGroup"),
  {
    suspense: true,
  }
);
const Register_to_host = () => {
  const [showA, setShowA] = useState(false);
  const [showB, setShowB] = useState(false);
  const [showC, setShowC] = useState(false);
  const [showD, setShowD] = useState(false);
  const [showE, setShowE] = useState(false);
  const [showF, setShowF] = useState(false);

  const toggleButtonA = () => {
    setShowA(!showA);
  };

  const toggleButtonB = () => {
    setShowB(!showB);
  };

  const toggleButtonC = () => {
    setShowC(!showC);
  };

  const toggleButtonD = () => {
    setShowD(!showD);
  };

  const toggleButtonE = () => {
    setShowE(!showE);
  };

  const toggleButtonF = () => {
    setShowF(!showF);
  };

  return (
    <>
      <Head>
        <title>Golfhom | Register As Host</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        {/*----------------              TOP IMAGE SECTION         --------------------*/}

        <div className={RegisterToHost.targetBall}>
          <Image
            src="https://golf-hom-latest-assets.s3.amazonaws.com/images/targetBall.png"
            alt="Target Ball"
            fill
            className={RegisterToHost.imgTargetBall}
          ></Image>
        </div>

        {/*--------------------------        REGISTER COLUMN CONTAINER       ----------------------- */}

        <div className={RegisterToHost.registerParent}>
          <Col md={6} className={RegisterToHost.columnA}>
            <h3 className={RegisterToHost.golfheading}>
              Become a Golfhōm Host!
            </h3>
            <p className={RegisterToHost.para}>
              Host golf travelers, monetize your property.
            </p>
          </Col>

          <Col md={4} className={RegisterToHost.columnB}>
            <div>
              <h5 className={RegisterToHost.registerTitle}>Register</h5>
              <div className={RegisterToHost.registerContent}>
                <Col className={RegisterToHost.inputParent}>
                  <div>
                    <Input
                      className={RegisterToHost.inputA}
                      type="text"
                      placeholder="Enter User name"
                    ></Input>
                  </div>

                  <div>
                    <Input
                      className={RegisterToHost.inputB}
                      type="email"
                      placeholder="Email"
                    ></Input>
                  </div>

                  <div>
                    <Input
                      className={RegisterToHost.inputC}
                      type="password"
                      placeholder="Password"
                    ></Input>
                  </div>

                  <div>
                    <Input
                      className={RegisterToHost.inputD}
                      type="password"
                      placeholder="Repeat Password"
                    ></Input>
                  </div>
                </Col>

                <Row>
                  <div>
                    <Checkbox className={RegisterToHost.agreeOptionA}>
                      I agree with your{" "}
                      <Link
                        className={RegisterToHost.conditions_links}
                        href="/term_and_conditions"
                      >
                        {" "}
                        Terms & Conditions
                      </Link>
                    </Checkbox>
                  </div>
                  <div>
                    <Checkbox className={RegisterToHost.agreeOptionB}>
                      I agree with your{" "}
                      <Link
                        className={RegisterToHost.conditions_links}
                        href="/privacy"
                        target="_blank"
                      >
                        {" "}
                        Privacy Policy{" "}
                      </Link>
                    </Checkbox>
                  </div>
                </Row>

                <Button className={RegisterToHost.registerBtn}>Register</Button>
              </div>
            </div>
          </Col>
        </div>
      </section>

      {/* ---------------------------        THREE COLUMN CONTAINER            -------------------------- */}

      <Container>
        <Row>
          <Col md={4} className={RegisterToHost.textColumn}>
            <h4 className={RegisterToHost.threeColumnTitle}>
              Why Choose Golfhōm?
            </h4>
            <p className={RegisterToHost.threeColumnPara}>
              Golfers love their sport, and many love to travel as well. Those
              that love both are tired of stumbling around on other vacation
              rental platforms trying to place a rental near their favorite
              course or tournament. Golf-travelers are searching for the next
              rental on Golfhōm right now, will they find your home?
            </p>
          </Col>

          <Col md={4} className={RegisterToHost.textColumn}>
            <h4 className={RegisterToHost.threeColumnTitle}>
              Booking Made Easy.
            </h4>
            <p className={RegisterToHost.threeColumnPara}>
              Travelers can search for their next Golfhōm by any of the world's
              38,000+ golf courses, as well as by major tournament. Easy to
              locate, easy to book, golf-industry partner resources and
              discounts...
            </p>
          </Col>

          <Col md={4} className={RegisterToHost.textColumn}>
            <h4 className={RegisterToHost.threeColumnTitle}>
              Market to Your Key Clientele.
            </h4>
            <p className={RegisterToHost.threeColumnPara}>
              If you own a vacation rental property in the vicinity of a golf
              course, golf-travelers are a key market for you. Golfers are
              increasingly moving their search efforts over to Golfhōm, easier
              to search, more golf to enjoy.
            </p>
          </Col>
        </Row>
      </Container>

      {/* ---------------------------        TEXT IN SIDE OF IMAGE CONTAINER         ----------------------------- */}

      <Container className={RegisterToHost.textImageParent}>
        <h3 className={RegisterToHost.hostTitle}>How To Host</h3>

        <Row className={RegisterToHost.rowContentA}>
          <Col md={6} className={RegisterToHost.textParentA}>
            <h4 className={RegisterToHost.textTitle}>
              1. List Your Home or Condo
            </h4>
            <p className={RegisterToHost.paragraph}>
              Complete our simple listing loop, tell us which course(s) the home
              is within 2 miles of, and we’ll promote your property to
              golf-travelers the world over.
            </p>
          </Col>

          <Col md={6} className={RegisterToHost.imageParent}>
            <Image
              src="https://golf-hom-latest-assets.s3.amazonaws.com/images/condoView.png"
              alt="condoView"
              fill
              className={RegisterToHost.condoImage}
            ></Image>
          </Col>
        </Row>

        <Row className={RegisterToHost.rowContentA}>
          <Col md={6} className={RegisterToHost.imageParent}>
            <Image
              src="https://golf-hom-latest-assets.s3.amazonaws.com/images/lunch.svg"
              alt="condoView"
              fill
              className={RegisterToHost.lunchImage}
            ></Image>
          </Col>

          <Col md={6} className={RegisterToHost.textParentB}>
            <h4 className={RegisterToHost.textTitle}>
              {" "}
              2. Welcome Your Guests
            </h4>
            <p className={RegisterToHost.paragraph}>
              Once our golf travelers have located and booked your home, be sure
              to deliver a clean and reliable accommodation. For safety and
              reliability, make sure all communications and payments are made on
              our site.
            </p>
          </Col>
        </Row>

        <Row className={RegisterToHost.rowContentA}>
          <Col md={6} className={RegisterToHost.textParentC}>
            <h4 className={RegisterToHost.textTitle}>3. Earn Money</h4>
            <p className={RegisterToHost.paragraph}>
              Golfhōm pays out to hosts approximately 48 hours after the
              check-in date if no complaints have been registered. You set the
              price, we pay out promptly!
            </p>
          </Col>

          <Col md={6} className={RegisterToHost.imageParent}>
            <Image
              src="https://golf-hom-latest-assets.s3.amazonaws.com/images/earnMoney.webp"
              alt="condoView"
              fill
              className={RegisterToHost.earnMoney}
            ></Image>
          </Col>
        </Row>
      </Container>

      {/* ---------------------------      FREQUENTLY ASKED QUESTIONS      ------------------------------*/}

      <Container>
        <Row className={RegisterToHost.faqRow}>
          <Col md={6} className={RegisterToHost.textParentD}>
            <h3 className={RegisterToHost.textTitle}>
              Frequently Asked Questions
            </h3>
            <p className={RegisterToHost.paragraph}>
              Our team has provided answers below to some frequently asked
              questions. Please feel free to reach out to our help team if
              further information is needed, and thanks for booking with
              Golfhōm!
            </p>
          </Col>

          <Col md={6}>
            <div>
              <div>
                <div className={RegisterToHost.headingSign}>
                  <p className={RegisterToHost.faqTitle}>
                    How do I get more info about the property's amenities?
                  </p>
                  <Button
                    className={RegisterToHost.sign}
                    onClick={toggleButtonA}
                  >
                    {showA ? "-" : "+"}
                  </Button>
                </div>
                {showA && (
                  <div>
                    <p className={RegisterToHost.faqPara}>
                      You can find information on a property’s amenities on the
                      home’s profile page. Reach out to the host for more
                      specific information.
                    </p>
                  </div>
                )}
              </div>
            </div>

            <hr className={RegisterToHost.horizontaLine} />

            <div>
              <div className={RegisterToHost.headingSign}>
                <p className={RegisterToHost.faqTitle}>
                  I can't find my rental confirmation email. What Should I do?
                </p>
                <Button className={RegisterToHost.sign} onClick={toggleButtonB}>
                  {showB ? "-" : "+"}
                </Button>
              </div>
              {showB && (
                <div>
                  <p>
                    Please be sure to check your email inbox, junk, and spam
                    folders. If you still can’t find your confirmation, refer to
                    your Golfhōm admin area, or feel free to reach out to our
                    help team.
                  </p>
                </div>
              )}
            </div>

            <hr className={RegisterToHost.horizontaLine} />

            <div>
              <div className={RegisterToHost.headingSign}>
                <p className={RegisterToHost.faqTitle}>
                  I'll be arriving outside check-in hours. Can I still check in?
                </p>
                <Button className={RegisterToHost.sign} onClick={toggleButtonC}>
                  {showC ? "-" : "+"}
                </Button>
              </div>
              {showC && (
                <div>
                  <p>
                    This depends on the individual host, who will do their best
                    to meet your needs. We recommend dealing with arrival time
                    issues as early in the process as possible.
                  </p>
                </div>
              )}
            </div>

            <hr className={RegisterToHost.horizontaLine} />

            <div>
              <div className={RegisterToHost.headingSign}>
                <p className={RegisterToHost.faqTitle}>
                  I'd like to check out after the stated check-out time, is that
                  possible?
                </p>
                <Button className={RegisterToHost.sign} onClick={toggleButtonD}>
                  {showD ? "-" : "+"}
                </Button>
              </div>
              {showD && (
                <div>
                  <p>
                    A late check-out can only be arranged with the host, and is
                    not guaranteed. Reach out to see what can be arranged, and
                    keep in mind that availability and proper cleaning time have
                    to be accounted for.
                  </p>
                </div>
              )}
            </div>

            <hr className={RegisterToHost.horizontaLine} />

            <div>
              <div className={RegisterToHost.headingSign}>
                <p className={RegisterToHost.faqTitle}>
                  How Do I find out if my desired property allows pets?
                </p>
                <Button className={RegisterToHost.sign} onClick={toggleButtonE}>
                  {showE ? "-" : "+"}
                </Button>
              </div>
              {showE && (
                <div>
                  <p>
                    Pet policies should be clearly stated on the home’s profile
                    page. Reach out to the Host for any needed clarification, or
                    to see if a variance can be made.
                  </p>
                </div>
              )}
            </div>

            <hr className={RegisterToHost.horizontaLine} />

            <div>
              <div className={RegisterToHost.headingSign}>
                <p className={RegisterToHost.faqTitle}>
                  What payment methods are accepted by Golfhōm?
                </p>
                <Button className={RegisterToHost.sign} onClick={toggleButtonF}>
                  {showF ? "-" : "+"}
                </Button>
              </div>
              {showF && (
                <div>
                  <p>
                    Major credit cards and Paypal are acceptable payment methods
                    for properties listed on Golfhōm.com. You will have your
                    choice of payment methods at the tome of booking.
                  </p>
                </div>
              )}
            </div>
          </Col>
        </Row>
      </Container>

      {/*---------------------------      GO LIVE ON GOLFHOM NOW CONTAINER       ------------------------------ */}
      <Container>
        <Row className={RegisterToHost.goliveRow}>
          <Col md={6} className={RegisterToHost.textParentE}>
            <h4 className={RegisterToHost.listHomeTitle}>
              List Your Home or Condo Today! Go Live on Golfhōm Now
            </h4>
            <Button className={RegisterToHost.goliveBtn}>
              Go Live on Golfhom now
            </Button>
          </Col>
          <Col md={6} className={RegisterToHost.imageParent}>
            <Image
              src="https://golf-hom-latest-assets.s3.amazonaws.com/images/beach.webp"
              alt="Beach"
              fill
              className={RegisterToHost.beach}
            ></Image>
          </Col>
        </Row>
      </Container>

      {/*  -----------------------------           BOTTOM IMAGE SECTION         ----------------------------  */}

      <BottomSection />
    </>
  );
};

export default Register_to_host;
