import { React, useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import { Container, Col, Row, Button } from "react-bootstrap";
import ViewAllPropertyCss from "../../styles/ViewAllProperty.module.css";
import Image from "next/image";
import ViewAllProps from "../../../public/images/viewAllProps.png";
import BottomSection from "../../../common components/bottomGroup";
import { Pagination } from "antd";
import Florida from "../../../public/images/Florida.webp";
import Arizona from "../../../public/images/Arizona.webp";
import Sanfrancisco from "../../../public/images/SanFrancisco.webp";
import Newyork from "../../../public/images/NewYork.webp";
import { useRouter } from "next/router";
import axios from "axios";

const ViewAllProperty = () => {
  const RouterRef = useRouter();

  const [AllPropertyData, setAllPropertyData] = useState([{}]);

  useEffect(() => {
    const urlParams = new URLSearchParams(window.location.search);
    const ParamLatitude = urlParams.get("latitude");
    const ParamLongitude = urlParams.get("longitude");

    console.log(ParamLongitude);
    const GetPropDataFunc = async () => {
      try {
        const GetPropertyDataRes = await axios.get(
          `${process.env.NEXT_PUBLIC_API_URL}/v1/property?limit=12&latitude=${ParamLatitude}&longitude=${ParamLongitude}&page=1`
        );
        if (GetPropertyDataRes.status === 200) {
          setAllPropertyData(GetPropertyDataRes.data.data);
          console.log(GetPropertyDataRes.data.data);
        }
      } catch (error) {
        console.log("ERROR getting property data", error);
      }
    };
    GetPropDataFunc();

    return () => {
      GetPropDataFunc();
    };
  }, []);

  return (
    <>
      <Head>
        <title>Golfhom | View All Property</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* TOP IMAGE OF VIEW ALL PROPERTY PAGE */}
      <section className={ViewAllPropertyCss.headImage}>
        <Image
          src={ViewAllProps}
          alt="View All Property Image"
          fill
          className={ViewAllPropertyCss.imageChild}
        ></Image>
      </section>

      <section className={ViewAllPropertyCss.textContainer}>
        <Container>
          <h2 className={ViewAllPropertyCss.heading}>
            Find Great Vacation Rentals near Florida & Arizona
          </h2>

          <h2 className={ViewAllPropertyCss.golfCourse}> Golf Courses!</h2>

          <p className={ViewAllPropertyCss.para}>
            Arizona and Florida are renowned for their beautiful surroundings,
            outdoor lifestyles, & of course for having some of the world’s best
            golf courses! Golfhōm has a growing selection of golf
            course-vicinity vacation rentals that deliver the comforts of home,
            luxe amenities, and access to plenty of Arizona and Florida
            attractions!{" "}
          </p>

          <p className={ViewAllPropertyCss.para}>
            Golfhōm is transforming how golfers locate and book their next
            luxury golf vacation rental. Book with us today!
          </p>
        </Container>
      </section>

      <section className={ViewAllPropertyCss.view_prop_cards_Container}>
        <Container>
          <Row className={ViewAllPropertyCss.columnParent}>
            {AllPropertyData.map((Data, Index) => {
              return (
                <span
                  onClick={(e) => {
                    RouterRef.push({
                      pathname: `/search/${encodeURIComponent(Data.name)}/${
                        Data.id
                      }`,
                    });
                  }}
                  key={Index}
                  className={ViewAllPropertyCss.columnsA}
                >
                  <Image
                    fill
                    src={Data.imageUrl}
                    className={ViewAllPropertyCss.card_image}
                    alt="Florida"
                  ></Image>
                  <h4 className={ViewAllPropertyCss.countryName}>
                    {Data.name}
                  </h4>
                </span>
              );
            })}
          </Row>
        </Container>
      </section>

      {/* <Container className={ViewAllPropertyCss.pagination_container}>
        <Pagination
          colorText="#FF0000"
          showQuickJumper={false}
          showSizeChanger={false}
          defaultCurrent={2}
          total={500}
          className={ViewAllPropertyCss.pagination}
        />
      </Container> */}

      {/*  -----------------------------           BOTTOM IMAGE SECTION         ----------------------------  */}

      <BottomSection />
    </>
  );
};

export default ViewAllProperty;
